# Generated by Django 5.0.6 on 2024-07-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="subject",
            field=models.CharField(default="Default Subject", max_length=200),
        ),
    ]
