# Generated by Django 5.0.6 on 2024-07-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0002_contact_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="subject",
            field=models.CharField(max_length=200),
        ),
    ]
